# Docker Compose AWS環境用オーバーライド
# 使用方法: docker compose -f compose.yaml -f compose.aws.yaml up -d
#
# AWS環境での変更点:
# - PostgreSQL削除（RDSを使用）
# - MinIO削除（S3を使用）
# - Adminer削除（本番不要）
# - Cloudflare対応のNginx設定

services:
  # PostgreSQLは使用しない（RDSを使用）
  postgres:
    profiles:
      - disabled

  # MinIOは使用しない（S3を使用）
  minio:
    profiles:
      - disabled

  # Adminerは使用しない（本番不要）
  adminer:
    profiles:
      - disabled

  # Redis (EC2内で動作)
  redis:
    restart: always
    ports: []  # 外部公開しない
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: /fz99-lounge/redis
        awslogs-stream-prefix: redis
        awslogs-create-group: "true"

  # NestJS API本番設定
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
      target: production
      args:
        NODE_VERSION: 20-alpine
    container_name: fz99-lounge-api
    restart: always
    user: node
    environment:
      NODE_ENV: production
      PORT: ${API_PORT:-3000}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DISCORD_CALLBACK_URL: ${DISCORD_CALLBACK_URL}
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID}
      DISCORD_MATCH_ROOM_CATEGORY_ID: ${DISCORD_MATCH_ROOM_CATEGORY_ID}
      DISCORD_BOT_ENABLED: ${DISCORD_BOT_ENABLED:-true}
      DISCORD_MATCH_ANNOUNCE_CHANNEL_ID: ${DISCORD_MATCH_ANNOUNCE_CHANNEL_ID}
      DISCORD_MATCH_NOTIFY_ROLE_ID: ${DISCORD_MATCH_NOTIFY_ROLE_ID}
      DISCORD_REACTION_ROLE_CHANNEL_ID: ${DISCORD_REACTION_ROLE_CHANNEL_ID}
      DISCORD_REACTION_ROLE_EMOJI: ${DISCORD_REACTION_ROLE_EMOJI:-🔔}
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN}
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
      VAPID_SUBJECT: ${VAPID_SUBJECT}
      ENABLE_LOGIN_TRACKING: ${ENABLE_LOGIN_TRACKING:-true}
      MULTI_ACCOUNT_IP_THRESHOLD: ${MULTI_ACCOUNT_IP_THRESHOLD:-2}
      SUSPICIOUS_LOGIN_ALERT_DAYS: ${SUSPICIOUS_LOGIN_ALERT_DAYS:-30}
      # S3 (AWS) - IAMロール使用のためキー不要、S3_ENDPOINTは空でAWS S3を使用
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_REGION: ${S3_REGION:-ap-northeast-1}
      S3_ENDPOINT: ""
      S3_ACCESS_KEY_ID: ""
      S3_SECRET_ACCESS_KEY: ""
      NODE_OPTIONS: "--max-old-space-size=1024"
    volumes: []  # 本番環境ではボリュームマウントしない
    ports: []  # Nginx経由でのみアクセス
    depends_on:
      redis:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 768M
        reservations:
          cpus: '0.25'
          memory: 256M
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: /fz99-lounge/api
        awslogs-stream-prefix: api
        awslogs-create-group: "true"
    command: node dist/src/main
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => r.statusCode === 200 ? process.exit(0) : process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Next.js Web本番設定
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      target: production
      args:
        NODE_VERSION: 20-alpine
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
    container_name: fz99-lounge-web
    restart: always
    user: node
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
      NODE_OPTIONS: "--max-old-space-size=1024"
    volumes: []
    ports: []
    depends_on:
      api:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 768M
        reservations:
          cpus: '0.25'
          memory: 256M
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: /fz99-lounge/web
        awslogs-stream-prefix: web
        awslogs-create-group: "true"
    command: node server.js

  # Nginx (Cloudflare対応)
  nginx:
    image: nginx:alpine
    container_name: fz99-lounge-nginx
    restart: always
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # AWS用設定を使用（Cloudflare IP対応）
      - ./docker/nginx/aws.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx_cache:/var/cache/nginx
    ports:
      - "80:80"
    depends_on:
      - api
      - web
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: /fz99-lounge/nginx
        awslogs-stream-prefix: nginx
        awslogs-create-group: "true"
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 5s
      retries: 3
    profiles: []  # 常に起動

volumes:
  nginx_cache:
    driver: local
