# Docker Compose AWS環境用オーバーライド
# 使用方法: docker compose -f compose.yaml -f compose.aws.yaml up -d
#
# AWS環境での変更点:
# - PostgreSQL削除（RDSを使用）
# - MinIO削除（S3を使用）
# - Adminer削除（本番不要）
# - Cloudflare対応のNginx設定

services:
  # PostgreSQLは使用しない（RDSを使用）
  postgres:
    profiles:
      - disabled

  # MinIOは使用しない（S3を使用）
  minio:
    profiles:
      - disabled

  # Adminerは使用しない（本番不要）
  adminer:
    profiles:
      - disabled

  # Redis (EC2内で動作)
  redis:
    restart: always
    ports: []  # 外部公開しない
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # NestJS API本番設定
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
      target: production
      args:
        NODE_VERSION: 20-alpine
    container_name: fz99-lounge-api
    restart: always
    user: node
    environment:
      NODE_ENV: production
      PORT: ${API_PORT:-3000}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DISCORD_CALLBACK_URL: ${DISCORD_CALLBACK_URL}
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID}
      DISCORD_MATCH_ROOM_CATEGORY_ID: ${DISCORD_MATCH_ROOM_CATEGORY_ID}
      DISCORD_BOT_ENABLED: ${DISCORD_BOT_ENABLED:-true}
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN}
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
      VAPID_SUBJECT: ${VAPID_SUBJECT}
      ENABLE_LOGIN_TRACKING: ${ENABLE_LOGIN_TRACKING:-true}
      MULTI_ACCOUNT_IP_THRESHOLD: ${MULTI_ACCOUNT_IP_THRESHOLD:-2}
      SUSPICIOUS_LOGIN_ALERT_DAYS: ${SUSPICIOUS_LOGIN_ALERT_DAYS:-30}
      # S3 (AWS)
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_REGION: ${S3_REGION:-ap-northeast-1}
      # IAM Roleを使用するためエンドポイント/キーは不要
      NODE_OPTIONS: "--max-old-space-size=1024"
    volumes: []  # 本番環境ではボリュームマウントしない
    ports: []  # Nginx経由でのみアクセス
    depends_on:
      redis:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 768M
        reservations:
          cpus: '0.25'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    command: node dist/main

  # Next.js Web本番設定
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      target: production
      args:
        NODE_VERSION: 20-alpine
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: fz99-lounge-web
    restart: always
    user: node
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NODE_OPTIONS: "--max-old-space-size=1024"
    volumes: []
    ports: []
    depends_on:
      api:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 768M
        reservations:
          cpus: '0.25'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    command: npm start

  # Nginx (Cloudflare対応)
  nginx:
    image: nginx:alpine
    container_name: fz99-lounge-nginx
    restart: always
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # AWS用設定を使用（Cloudflare IP対応）
      - ./docker/nginx/conf.d/aws.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx_cache:/var/cache/nginx
    ports:
      - "80:80"
    depends_on:
      - api
      - web
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 5s
      retries: 3
    profiles: []  # 常に起動

volumes:
  nginx_cache:
    driver: local
